version: "3.8"

services:
  frontend:
    build:
      context: ./interview-frontend
      dockerfile: Dockerfile
    container_name: interview-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - NEXT_PUBLIC_LIVEKIT_URL=${LIVEKIT_URL}
      - CUSTOM_API_SECRET=${CUSTOM_API_SECRET}

  backend:
    build:
      context: ./interview-backend
      dockerfile: Dockerfile
    container_name: interview-backend
    restart: unless-stopped
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - LIVEKIT_URL=${LIVEKIT_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - BREEZY_ROCKETDEVS_USERNAME=${BREEZY_ROCKETDEVS_USERNAME}
      - BREEZY_ROCKETDEVS_PASSWORD=${BREEZY_ROCKETDEVS_PASSWORD}
      - BREEZY_HIVEMINDS_USERNAME=${BREEZY_HIVEMINDS_USERNAME}
      - BREEZY_HIVEMINDS_PASSWORD=${BREEZY_HIVEMINDS_PASSWORD}
      - REDIS_HOST=redis
  
  # THE FOLLOWING IS NEEDED TO MAKE RECORDINGS ON A DUMMY SERVER WITHOUT
  # LIVEKIT PROD EGRESS FEES!!!
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  hr_livekit_egress:
    image: livekit/egress:v1.9
    container_name: hr_livekit_egress
    depends_on:
      - redis
    environment:
      - EGRESS_CONFIG_FILE=/out/config.yaml
    volumes:
      - ./config/egress:/out

  hr_livekit:
    image: livekit/livekit-server:v1.8
    container_name: hr_livekit
    command: --config=/out/config.yaml
    depends_on:
      - redis
    ports:
      - "7880:7880"
    volumes:
      - ./config/livekit:/out
