version: "3.8"

services:
  frontend:
    build:
      context: ./interview-frontend
      dockerfile: Dockerfile
    container_name: interview-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - NEXT_PUBLIC_LIVEKIT_URL=${LIVEKIT_URL}

  backend:
    build:
      context: ./interview-backend
      dockerfile: Dockerfile
    container_name: interview-backend
    restart: unless-stopped
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - LIVEKIT_URL=${LIVEKIT_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - BREEZY_ROCKETDEVS_USERNAME=${BREEZY_ROCKETDEVS_USERNAME}
      - BREEZY_ROCKETDEVS_PASSWORD=${BREEZY_ROCKETDEVS_PASSWORD}
      - BREEZY_HIVEMINDS_USERNAME=${BREEZY_HIVEMINDS_USERNAME}
      - BREEZY_HIVEMINDS_PASSWORD=${BREEZY_HIVEMINDS_PASSWORD}
